# 实例名称，用于在同一台机器上标识此节点
instance_name = ""
# 主机名，用于标识此设备的主机名
hostname = ""
# 实例 ID，一般为 UUID，在同一个虚拟网络中唯一
instance_id = ""
# 此节点的虚拟网 IPv4 地址，如果为空，则此节点将仅转发数据包，不会创建 TUN 设备
ipv4 = ""
# 由 Easytier 自动确定并设置IP地址，默认从10.0.0.1开始。警告：在使用 DHCP 时，如果网络中出现 IP 冲突，IP 将自动更改
dhcp = false

# 监听器列表，用于接受连接
listeners = [
"tcp://0.0.0.0:11010",
"udp://0.0.0.0:11010",
"wg://0.0.0.0:11011",
"ws://0.0.0.0:11011/",
"wss://0.0.0.0:11012/",
]

# 退出节点列表
exit_nodes = [
]

# 用于管理的 RPC 门户地址
rpc_portal = "127.0.0.1:15888"

[network_identity]
# 网络名称，用于标识虚拟网络
network_name = ""
# 网络密钥，用于验证此节点属于虚拟网络
network_secret = ""

# 这里是对等连接节点配置，可以多段配置
[[peer]]
uri = "tcp://public.easytier.top:11010"

[[peer]]
uri = "udp://public.easytier.top:11010"

# 这里是子网代理节点配置，可以有多段配置
[[proxy_network]]
cidr = "10.0.1.0/24"

[[proxy_network]]
cidr = "10.0.2.0/24"

# WireGuard 配置信息
[vpn_portal_config]
# WireGuard 客户端所在的网段，下面为示例
client_cidr = "10.14.14.0/24"
#wg所监听的端口(请勿和listeners的wg冲突)
wireguard_listen = "0.0.0.0:11012"

[flags]
# 连接到对等节点使用的默认协议
default_protocol = "tcp"
# TUN 设备名称，如果为空，则使用默认名称
dev_name = ""
# 禁用p2p
disable_p2p = false
# 是否启用加密
enable_encryption = true
# 是否启用 IPv6 支持
enable_ipv6 = true
# TUN 设备的 MTU
mtu = 1380
# 延迟优先模式，将尝试使用最低延迟路径转发流量，默认使用最短路径
latency_first = false
# 将本节点配置为退出节点
enable_exit_node = false
# 禁用 TUN 设备
no_tun = false
# 为子网代理启用 smoltcp 堆栈
use_smoltcp = false
# 仅转发白名单网络的流量，支持通配符字符串。多个网络名称间可以使用英文空格间隔。如果该参数为空，则禁用转发。默认允许所有网络。例如：'*'（所有网络），'def*'（以def为前缀的网络），'net1 net2'（只允许net1和net2）
foreign_network_whitelist = "*"